version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Run Tests
          command: mvn clean test
      - store_artifacts:
          path: target/surefire-reports
          destination: junit-reports
    executor:

workflows:
  version: 2
  build-and-test:
    jobs:
      - buildversion: 